### ISSUE TITLE
Explain how to use pouch-db

### ISSUE THREAD

**Issue by mpruessmeier** [hubgit/pouch-db#1]
Hi.

Can you please explain how to use this polymer element in README.md

Thanks, Marc

**Comment by hubgit** [comment]
@mpruessmeier All it does is include PouchDB, so usage is as in [the official documentation](http://pouchdb.com/). The version here is probably out of date by now, though - it hasn't been updated for quite a long time.

**Comment by hubgit** [comment]
I've updated the code to import pouchdb.js from the official repository, and added to the README.

**Comment by mpruessmeier** [comment]
Thanks, I'll try it out then
